site_name: Instrutoria Prestamista
site_url: https://evolares.github.io/instrutoria-prestamista/

theme:
  name: material
  language: pt-BR

extra_css:
  - stylesheets/extra.css

nav:
  - Início: index.md

  - Formação:
      - Módulo 01: formacao/apostila-01.md
      - Módulo 02: formacao/apostila-02.md
      - Módulo 03: formacao/apostila-03.md
      - Módulo 04: formacao/apostila-04.md
      - Módulo 05: formacao/apostila-05.md
      - Módulo 06: formacao/apostila-06.md
      - Módulo 07: formacao/apostila-07.md
      - Módulo 08: formacao/apostila-08.md
      - Módulo 09: formacao/apostila-09.md
      - Módulo 10: formacao/apostila-10.md

  - Avaliações:
      - Diagnóstico: avaliacoes/diagnostico.md
      - Certificação: avaliacoes/certificacao.md

  - Apoio:
      - Inscrição: apoio/inscricao.md